/**@description 公共事件定义 */
export enum CommonEvent{
    /**@description protobuf消息测试 */
    TEST_PROTO_MSG = "TEST_PROTO_MSG",
    /**@description 二进制流消息测试 */
    TEST_BINARY_MSG = "TEST_BINARY_MSG",
    /**@description json消息测试 */
    TEST_JSON_MSG = "TEST_JSON_MSG",
    /**@description 大厅连接成功 */
    LOBBY_SERVICE_CONNECTED = "LOBBY_SERVICE_CONNECTED",
    /**@description 大厅连接断开 */
    LOBBY_SERVICE_CLOSE = "LOBBY_SERVICE_CLOSE",
    /**@description 游戏连接成功 */
    GAME_SERVICE_CONNECTED = "GAME_SERVICE_CONNECTED",
    /**@description 游戏连接断开 */
    GAME_SERVICE_CLOSE = "GAME_SERVICE_CLOSE",
    /**@description 聊天连接成功 */
    CHAT_SERVICE_CONNECTED = "CHAT_SERVICE_CONNECTED",
    /**@description 聊天连接断开 */
    CHAT_SERVICE_CLOSE = "CHAT_SERVICE_CLOSE",
}